#volumenes host
version: '3'
services:
  web:
    container_name: nginxtest
    image: nginx
    ports:
      - "8081:80"
    volumes:
       - "C:\\Users\\RLAñez\\Desktop\\Git Personal\\docker\\docker-compose\\Volumenes\\html:/usr/share/nginx/html"
volumes:
  vol2: